[package]
name = "macaroon"
version = "0.1.0"
authors = ["Jack Lund <jackl@geekheads.net>"]

[dependencies]
log = "0.3.6"
rustc-serialize = "0.3.22"
serde = "0.9.2"
serde_derive = "0.9.2"
serde_json = "0.9.2"
sodiumoxide = "0.0.13"

[dev-dependencies]
env_logger = "0.3"
time = "0.1.36"